name: Automated Regressive Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regressive_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Running Tests
        run: |
          python -m robot -d regressive_tests tests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: regressive_tests
          path: regressive_tests/*